#!/bin/bash

#Default directory

TIMEKPRDIR=/var/lib/timekpr

if [ $# -ne 1 ]; then
	echo "Usage $(basename $0) <username>"
	exit
fi

#if [[ -e "$TIMEKPRDIR/$1.allow" ]]; then
#	rm "$TIMEKPRDIR/$1.allow"
#	echo
#	echo "$1 has been disallowed to log in outside of normal logon hours"
#	echo
#else
	touch $TIMEKPRDIR/$1.allow
	echo
	echo "$1 has been allowed to log in outside of normal logon hours"
	echo
#fi

