#!/bin/bash

# timekpr-unlock username
# Resets/unsets the old expiration date of the username

if [[ "$1" == "" ]]; then
	echo "Usage: timekpr-unlock username"
	exit
fi

#Default directory
TIMEKPRDIR=/var/lib/timekpr

#remove lock, reset old expiration date
if [[ -e $TIMEKPRDIR/$1.lock ]]; then
	# Get old expiration date
	oldexpiration=$(cat $TIMEKPRDIR/$1.lock)
	if [[ "$oldexpiration" == "" ]]; then
		oldexpdate=""
	else
		oldexpdate=$(date -d "1970-01-01 $oldexpiration days" +%Y-%m-%d)
	fi
	echo "Attempting to remove $1.lock.."
	rm -f $TIMEKPRDIR/$1.lock
	echo "Setting the old expiration date for $1.."
	usermod -e "$oldexpdate" $1
else
	echo "$1.lock not found"
fi
